title: "AmanithVG, a software OpenVG library for 2D vector graphics rendering"
description: "OpenVG 1.1 library for 2D vector graphics rendering"
description2: 
keywords: "amanithvg openvg vector graphics 2D library software rendering openvg1.1 khronos" 
url: "https://www.amanithvg.com"
enforce_ssl: "www.amanithvg.com"
google_analytics: "UA-257732-1"
copyright: "(C) 2023 Mazatech, Srl"
vatid: "VAT ID IT03498460405"
rights: "All rights reserved"
product_name: "AmanithVG"
company_name_ext: "Mazatech, Srl"
company_email: "info@mazatech.com"
facebook_username: "mazatechsrl"
twitter_username: "Mazatech1"
github_username: "Mazatech"
collections:
  docs:
    output: true
assets:
  sources:
    - _assets
    - _assets/fonts
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  sass_dir: _includes
  style: compressed
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
plugins: 
  - jekyll-sitemap
